interface BrandLogoProps {
  className?: string;
}

/**
 * The SI-MPOK NORI seal ships as a single transparent PNG (generated by
 * `scripts/make-brand-assets.ts`), so it needs no light/dark variant swap the
 * way the old wordmark SVGs did.
 */
export function BrandLogo({ className = "" }: BrandLogoProps) {
  return (
    <img
      src="/brand/si-mpok-nori-logo.png"
      alt="SI-MPOK NORI"
      width={512}
      height={512}
      className={className}
    />
  );
}
